const AllSkillSets = [
    { value: 'communication', label: 'Communication' },
    { value: 'teamwork', label: 'Teamwork' },
    { value: 'leadership', label: 'Leadership' },
    { value: 'problem-solving', label: 'Problem Solving' },
    { value: 'time-management', label: 'Time Management' },
    { value: 'critical-thinking', label: 'Critical Thinking' },
    { value: 'adaptability', label: 'Adaptability' },
    { value: 'interpersonal-skills', label: 'Interpersonal Skills' },
    { value: 'public-speaking', label: 'Public Speaking' },
    { value: 'conflict-resolution', label: 'Conflict Resolution' },
    { value: 'event-planning', label: 'Event Planning' },
    { value: 'social-media-management', label: 'Social Media Management' },
    { value: 'data-entry', label: 'Data Entry' },
    { value: 'technical-writing', label: 'Technical Writing' },
    { value: 'research', label: 'Research' },
    { value: 'graphic-design', label: 'Graphic Design' },
    { value: 'web-development', label: 'Web Development' },
    { value: 'digital-marketing', label: 'Digital Marketing' },
    { value: 'fundraising', label: 'Fundraising' },
    { value: 'first-aid', label: 'First Aid' },
    { value: 'coaching', label: 'Coaching' },
    { value: 'teaching', label: 'Teaching' },
    { value: 'counseling', label: 'Counseling' },
    { value: 'project-management', label: 'Project Management' },
    { value: 'foreign-languages', label: 'Foreign Languages' },
    { value: 'photography', label: 'Photography' },
    { value: 'video-editing', label: 'Video Editing' },
  ];
  

export default AllSkillSets